In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import autorootcwd
import os
import json

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

In [9]:
DIR = './results/beatwise_sampling'
expts = os.listdir(DIR)
rows = []
for e in expts:
    with open(f"{DIR}/{e}/metadata.json") as f:
        args = json.load(f)

    args = args['args']
    exp_name = args['exp_name']

    if not os.path.exists(f"{DIR}/{e}/val_metrics.json"):
        print(f"Skipping {e} because val_metrics.json does not exist")
        continue
    
    with open(f"{DIR}/{e}/val_metrics.json") as f:
        val = json.load(f)

    rows.append({
        'exp_name': exp_name,
        'acc': val['mean']['acc'],
        'root': val['mean']['root'],
        'third': val['mean']['third'],
        'seventh': val['mean']['seventh'],
        'mirex': val['mean']['mirex'],
        # 'mean_acc_class': val['class_wise']['acc']['mean'],
        # 'median_acc_class': val['class_wise']['acc']['median'],
    })
 

df = pd.DataFrame(rows)

In [12]:
df[~df['exp_name'].isin(['perfect_beats_train_only', 'feed_transitions', ''])].sort_values(by='exp_name')

,exp_name,acc,root,third,seventh,mirex
5,beat_interval_0.25,62.264462,81.348199,78.327109,64.496979,79.584662
8,beat_interval_0.5,62.793595,81.533854,78.573272,65.115033,79.929045
0,beat_interval_1,62.278038,81.306063,78.065110,64.588300,80.008351
4,beat_interval_2,56.427320,74.688650,71.605765,58.451085,73.378397
7,beat_interval_4,50.795754,68.043367,64.493542,52.764954,67.239474
6,none,62.464270,81.675712,78.237737,64.748798,80.181424
2,perfect_beats_train_and_test,61.057359,79.572439,76.126438,63.350109,90.404057